# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/samuel/lab_2_new/mips.xdc

# Block Designs: bd/data_path/data_path.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_path || ORIG_REF_NAME==data_path} -quiet] -quiet

# IP: bd/data_path/ip/data_path_Program_Counter_Adder_0_0/data_path_Program_Counter_Adder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_path_Program_Counter_Adder_0_0 || ORIG_REF_NAME==data_path_Program_Counter_Adder_0_0} -quiet] -quiet

# IP: bd/data_path/ip/data_path_instmem_0_0/data_path_instmem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_path_instmem_0_0 || ORIG_REF_NAME==data_path_instmem_0_0} -quiet] -quiet

# IP: bd/data_path/ip/data_path_Project_Counter_0_0/data_path_Project_Counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_path_Project_Counter_0_0 || ORIG_REF_NAME==data_path_Project_Counter_0_0} -quiet] -quiet

# IP: bd/data_path/ip/data_path_Control_0_0/data_path_Control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_path_Control_0_0 || ORIG_REF_NAME==data_path_Control_0_0} -quiet] -quiet

# IP: bd/data_path/ip/data_path_regfile_0_0/data_path_regfile_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_path_regfile_0_0 || ORIG_REF_NAME==data_path_regfile_0_0} -quiet] -quiet

# IP: bd/data_path/ip/data_path_alu_control_0_0/data_path_alu_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_path_alu_control_0_0 || ORIG_REF_NAME==data_path_alu_control_0_0} -quiet] -quiet

# IP: bd/data_path/ip/data_path_ALU_0_0/data_path_ALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_path_ALU_0_0 || ORIG_REF_NAME==data_path_ALU_0_0} -quiet] -quiet

# IP: bd/data_path/ip/data_path_xlslice_0_0/data_path_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_path_xlslice_0_0 || ORIG_REF_NAME==data_path_xlslice_0_0} -quiet] -quiet

# IP: bd/data_path/ip/data_path_xlslice_1_0/data_path_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_path_xlslice_1_0 || ORIG_REF_NAME==data_path_xlslice_1_0} -quiet] -quiet

# IP: bd/data_path/ip/data_path_xlslice_2_0/data_path_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_path_xlslice_2_0 || ORIG_REF_NAME==data_path_xlslice_2_0} -quiet] -quiet

# IP: bd/data_path/ip/data_path_xlslice_3_0/data_path_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_path_xlslice_3_0 || ORIG_REF_NAME==data_path_xlslice_3_0} -quiet] -quiet

# IP: bd/data_path/ip/data_path_xlslice_4_0/data_path_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_path_xlslice_4_0 || ORIG_REF_NAME==data_path_xlslice_4_0} -quiet] -quiet

# IP: bd/data_path/ip/data_path_xlconstant_0_0/data_path_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_path_xlconstant_0_0 || ORIG_REF_NAME==data_path_xlconstant_0_0} -quiet] -quiet

# IP: bd/data_path/ip/data_path_xlconstant_1_0/data_path_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_path_xlconstant_1_0 || ORIG_REF_NAME==data_path_xlconstant_1_0} -quiet] -quiet

# IP: bd/data_path/ip/data_path_xlslice_5_0/data_path_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_path_xlslice_5_0 || ORIG_REF_NAME==data_path_xlslice_5_0} -quiet] -quiet

# XDC: bd/data_path/data_path_ooc.xdc
