#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Feb 26 19:29:36 EST 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 93fba2ecc7b34973a318b56b235b7ecf --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xlslice_v1_0_2 -L xlconstant_v1_1_6 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot data_path_tb_behav xil_defaultlib.data_path_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 93fba2ecc7b34973a318b56b235b7ecf --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xlslice_v1_0_2 -L xlconstant_v1_1_6 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot data_path_tb_behav xil_defaultlib.data_path_tb xil_defaultlib.glbl -log elaborate.log

